name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd /var/www/ch6dabc3a9/www/phoenyx.com.ua
          git pull origin main
